In [39]:
from dataset.compas import CompasDataset
from dataset import dataset_loader
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim

In [40]:
%reload_ext autoreload
%autoreload 2

In [41]:
name = 'compas'
dataset_ares = dataset_loader(name, data_path='rawdata/', dropped_features=[], n_bins=None)

dataset = CompasDataset(dataset_ares=dataset_ares)
df = dataset.get_dataframe()

In [80]:
dataset_ares.categorical_features['compas']

['Sex', 'Age_Cat', 'Race', 'C_Charge_Degree']

In [97]:
dataset_ares.data

Sex = Female  Sex = Male  Age_Cat = Less than 25  Age_Cat = 25 - 45  \
0              0.0         1.0                     0.0                0.0   
1              0.0         1.0                     0.0                1.0   
2              0.0         1.0                     1.0                0.0   
3              0.0         1.0                     0.0                1.0   
4              0.0         1.0                     0.0                1.0   
...            ...         ...                     ...                ...   
6167           0.0         1.0                     1.0                0.0   
6168           0.0         1.0                     1.0                0.0   
6169           0.0         1.0                     0.0                0.0   
6170           1.0         0.0                     0.0                1.0   
6171           1.0         0.0                     1.0                0.0   

      Age_Cat = Greater than 45  Race = African-American  Race = Asian  \
0                           1.0                      0.0           0.0   
1                           0.0                      1.0           0.0   
2                           0.0                      1.0           0.0   
3                           0.0                      0.0           0.0   
4                           0.0                      0.0           0.0   
...                         ...                      ...           ...   
6167                        0.0                      1.0           0.0   
6168                        0.0                      1.0           0.0   
6169                        1.0                      0.0           0.0   
6170                        0.0                      1.0           0.0   
6171                        0.0                      0.0           0.0   

      Race = Caucasian  Race = Hispanic  Race = Native American  Race = Other  \
0                  0.0              0.0                     0.0           1.0   
1                  0.0              0.0                     0.0           0.0   
2                  0.0              0.0                     0.0           0.0   
3                  0.0              0.0                     0.0           1.0   
4                  1.0              0.0                     0.0           0.0   
...                ...              ...                     ...           ...   
6167               0.0              0.0                     0.0           0.0   
6168               0.0              0.0                     0.0           0.0   
6169               0.0              0.0                     0.0           1.0   
6170               0.0              0.0                     0.0           0.0   
6171               0.0              1.0                     0.0           0.0   

      C_Charge_Degree = F  C_Charge_Degree = M  Priors_Count  Time_Served  \
0                     1.0                  0.0           0.0          0.0   
1                     1.0                  0.0           0.0         10.0   
2                     1.0                  0.0           4.0          1.0   
3                     0.0                  1.0           0.0          1.0   
4                     1.0                  0.0          14.0          6.0   
...                   ...                  ...           ...          ...   
6167                  1.0                  0.0           0.0          1.0   
6168                  1.0                  0.0           0.0          1.0   
6169                  1.0                  0.0           0.0          1.0   
6170                  0.0                  1.0           3.0          1.0   
6171                  1.0                  0.0           2.0          1.0   

      Status  
0        1.0  
1        0.0  
2        0.0  
3        1.0  
4        0.0  
...      ...  
6167     1.0  
6168     1.0  
6169     1.0  
6170     1.0  
6171     0.0  

[6172 rows x 16 columns]

In [100]:
dataset_ares.features_tree

{'Sex': ['Sex = Female', 'Sex = Male'],
 'Age_Cat': ['Age_Cat = Less than 25',
  'Age_Cat = 25 - 45',
  'Age_Cat = Greater than 45'],
 'Race': ['Race = African-American',
  'Race = Asian',
  'Race = Caucasian',
  'Race = Hispanic',
  'Race = Native American',
  'Race = Other'],
 'C_Charge_Degree': ['C_Charge_Degree = F', 'C_Charge_Degree = M'],
 'Priors_Count': [],
 'Time_Served': []}

In [81]:
dataset_ares.continuous_features['compas']

['Priors_Count', 'Time_Served']

In [86]:
dataset_ares.bins

{}

In [87]:
dataset_ares.bins_tree

{}

In [99]:
dataset_ares.columns['compas']

['Sex',
 'Age_Cat',
 'Race',
 'C_Charge_Degree',
 'Priors_Count',
 'Time_Served',
 'Status']

In [93]:
dataset_ares.features

['Sex = Female',
 'Sex = Male',
 'Age_Cat = Less than 25',
 'Age_Cat = 25 - 45',
 'Age_Cat = Greater than 45',
 'Race = African-American',
 'Race = Asian',
 'Race = Caucasian',
 'Race = Hispanic',
 'Race = Native American',
 'Race = Other',
 'C_Charge_Degree = F',
 'C_Charge_Degree = M',
 'Priors_Count',
 'Time_Served',
 'Status']

In [91]:
dataset_ares.features_tree

{'Sex': ['Sex = Female', 'Sex = Male'],
 'Age_Cat': ['Age_Cat = Less than 25',
  'Age_Cat = 25 - 45',
  'Age_Cat = Greater than 45'],
 'Race': ['Race = African-American',
  'Race = Asian',
  'Race = Caucasian',
  'Race = Hispanic',
  'Race = Native American',
  'Race = Other'],
 'C_Charge_Degree': ['C_Charge_Degree = F', 'C_Charge_Degree = M'],
 'Priors_Count': [],
 'Time_Served': []}

In [75]:
dataset_ares.continuous_features

{'compas': ['Priors_Count', 'Time_Served'],
 'german_credit': ['Month-Duration', 'Credit-Amount', 'Age'],
 'adult_income': ['Age',
  'Fnlwgt',
  'Capital-Gain',
  'Capital-Loss',
  'Hours-Per-Week'],
 'default_credit': ['Limit_Bal',
  'Age',
  'Bill_Amt1',
  'Bill_Amt2',
  'Bill_Amt3',
  'Bill_Amt4',
  'Bill_Amt5',
  'Bill_Amt6',
  'Pay_Amt1',
  'Pay_Amt2',
  'Pay_Amt3',
  'Pay_Amt4',
  'Pay_Amt5',
  'Pay_Amt6'],
 'heloc': ['ExternalRiskEstimate',
  'MSinceOldestTradeOpen',
  'MSinceMostRecentTradeOpen',
  'AverageMInFile',
  'NumSatisfactoryTrades',
  'NumTrades60Ever2DerogPubRec',
  'NumTrades90Ever2DerogPubRec',
  'PercentTradesNeverDelq',
  'MSinceMostRecentDelq',
  'MaxDelq2PublicRecLast12M',
  'MaxDelqEver',
  'NumTotalTrades',
  'NumTradesOpeninLast12M',
  'PercentInstallTrades',
  'MSinceMostRecentInqexcl7days',
  'NumInqLast6M',
  'NumInqLast6Mexcl7days',
  'NetFractionRevolvingBurden',
  'NetFractionInstallBurden',
  'NumRevolvingTradesWBalance',
  'NumInstallTradesWBalance',

In [42]:
# name1 = 'german_credit'
# genrman_credit_AReS = dataset_loader(name1, data_path='rawdata/', dropped_features=[], n_bins=None)

In [43]:
# genrman_credit_AReS
# from dataset.german_credit import GermanCreditDataset
# dataset1 = GermanCreditDataset()

In [44]:
# df = dataset1.get_dataframe()

In [45]:
df.head(2)

Sex = Female  Sex = Male  Age_Cat = Less than 25  Age_Cat = 25 - 45  \
0           0.0         1.0                     0.0                0.0   
1           0.0         1.0                     0.0                1.0   

   Age_Cat = Greater than 45  Race = African-American  Race = Asian  \
0                        1.0                      0.0           0.0   
1                        0.0                      1.0           0.0   

   Race = Caucasian  Race = Hispanic  Race = Native American  Race = Other  \
0               0.0              0.0                     0.0           1.0   
1               0.0              0.0                     0.0           0.0   

   C_Charge_Degree = F  C_Charge_Degree = M  Priors_Count  Time_Served  Status  
0                  1.0                  0.0           0.0          0.0     1.0  
1                  1.0                  0.0           0.0         10.0     0.0

### 1.standardization

In [46]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

##### use the standardscaler

In [47]:
# scaler = StandardScaler()

# # # Assume df is your DataFrame and 'target' is your target column
# # X = df.drop(columns=['Status'])
# # Y = df['Status']
# X = df.drop(columns=['Risk'])
# Y = df['Risk']

# # Step 1: Split the Data
# X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# X_train_scaler = scaler.fit_transform(X_train)
# X_test_scaler = scaler.transform(X_test)

# print(f'X_train_scaler: {X_train_scaler.shape}')
# print(f'X_test_scaler: {X_test_scaler.shape}')

##### don't use the standardscaler

In [48]:
# Assume df is your DataFrame and 'target' is your target column
X = df.drop(columns=['Status'])
Y = df['Status']
# X = df.drop(columns=['Risk'])
# Y = df['Risk']

# Step 1: Split the Data
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

X_train_scaler = X_train.values
X_test_scaler = X_test.values

print(f'X_train_scaler: {X_train_scaler.shape}')
print(f'X_test_scaler: {X_test_scaler.shape}')

X_train_scaler: (4937, 15)
X_test_scaler: (1235, 15)


In [49]:
from models import PyTorchDNN, PyTorchLinearSVM, PyTorchRBFNet,PyTorchLogisticRegression

In [50]:
input_dim = X_train_scaler.shape[1]

model_svm = PyTorchLinearSVM(input_dim)

# 定义损失函数和优化器
criterion = nn.BCEWithLogitsLoss()  # 二分类任务中的损失函数
optimizer = optim.Adam(model_svm.parameters(), lr=0.01)  # 使用Adam优化器

# 数据转换为 PyTorch tensor 格式
X_train_tensor = torch.FloatTensor(X_train_scaler)
y_train_tensor = torch.FloatTensor(y_train).view(-1, 1)  # 确保y是二维



# 训练模型
epochs = 400  # 训练次数
for epoch in range(epochs):
    model_svm.train()  # 进入训练模式
    # 前向传播
    outputs = model_svm(X_train_tensor)
    # 计算损失
    loss = criterion(outputs, y_train_tensor)
    # 梯度清零
    optimizer.zero_grad()
    # 反向传播
    loss.backward()
    # 优化更新参数
    optimizer.step()
    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}')

Epoch [10/400], Loss: 0.6951
Epoch [20/400], Loss: 0.6518
Epoch [30/400], Loss: 0.6252
Epoch [40/400], Loss: 0.6183
Epoch [50/400], Loss: 0.6133
Epoch [60/400], Loss: 0.6109
Epoch [70/400], Loss: 0.6095
Epoch [80/400], Loss: 0.6088
Epoch [90/400], Loss: 0.6084
Epoch [100/400], Loss: 0.6082
Epoch [110/400], Loss: 0.6081
Epoch [120/400], Loss: 0.6080
Epoch [130/400], Loss: 0.6080
Epoch [140/400], Loss: 0.6080
Epoch [150/400], Loss: 0.6080
Epoch [160/400], Loss: 0.6080
Epoch [170/400], Loss: 0.6080
Epoch [180/400], Loss: 0.6080
Epoch [190/400], Loss: 0.6080
Epoch [200/400], Loss: 0.6080
Epoch [210/400], Loss: 0.6080
Epoch [220/400], Loss: 0.6080
Epoch [230/400], Loss: 0.6080
Epoch [240/400], Loss: 0.6080
Epoch [250/400], Loss: 0.6080
Epoch [260/400], Loss: 0.6080
Epoch [270/400], Loss: 0.6080
Epoch [280/400], Loss: 0.6080
Epoch [290/400], Loss: 0.6080
Epoch [300/400], Loss: 0.6080
Epoch [310/400], Loss: 0.6080
Epoch [320/400], Loss: 0.6080
Epoch [330/400], Loss: 0.6080
Epoch [340/400], Lo

### 2. initialize MODEL and DATA

In [51]:
from xai_cola.ml_model import Model
from xai_cola import data

In [52]:
column_names = X.columns.tolist()
column_names

['Sex = Female',
 'Sex = Male',
 'Age_Cat = Less than 25',
 'Age_Cat = 25 - 45',
 'Age_Cat = Greater than 45',
 'Race = African-American',
 'Race = Asian',
 'Race = Caucasian',
 'Race = Hispanic',
 'Race = Native American',
 'Race = Other',
 'C_Charge_Degree = F',
 'C_Charge_Degree = M',
 'Priors_Count',
 'Time_Served']

In [58]:
ml_model = Model(model_svm,'PYT')
compas_ares = data.NumpyData(
    data=X_test_scaler, 
    target_name="Status", 
    feature_names=column_names,
    )


##### Test counterfactual_explainer/ares.py

In [54]:
from xai_cola.counterfactual_explainer.ares import ARecourseS
ares_test = ARecourseS(
    ml_model=ml_model,
)

In [55]:
from xai_cola.data import AReS_dataInfo

In [56]:
X_test_scaler

array([[ 0.,  1.,  0., ...,  1., 13.,  7.],
       [ 0.,  1.,  0., ...,  1.,  1.,  1.],
       [ 0.,  1.,  0., ...,  0.,  2.,  0.],
       ...,
       [ 0.,  1.,  1., ...,  0.,  6.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  1.],
       [ 0.,  1.,  1., ...,  0.,  2., 86.]])

In [59]:
compas_ares.get_x()

Sex = Female  Sex = Male  Age_Cat = Less than 25  Age_Cat = 25 - 45  \
0              0.0         1.0                     0.0                1.0   
1              0.0         1.0                     0.0                1.0   
2              0.0         1.0                     0.0                1.0   
3              0.0         1.0                     1.0                0.0   
4              1.0         0.0                     1.0                0.0   
...            ...         ...                     ...                ...   
1230           0.0         1.0                     0.0                0.0   
1231           0.0         1.0                     0.0                1.0   
1232           0.0         1.0                     1.0                0.0   
1233           0.0         1.0                     0.0                1.0   
1234           0.0         1.0                     1.0                0.0   

      Age_Cat = Greater than 45  Race = African-American  Race = Asian  \
0                           0.0                      1.0           0.0   
1                           0.0                      0.0           0.0   
2                           0.0                      1.0           0.0   
3                           0.0                      0.0           0.0   
4                           0.0                      0.0           0.0   
...                         ...                      ...           ...   
1230                        1.0                      0.0           0.0   
1231                        0.0                      1.0           0.0   
1232                        0.0                      0.0           0.0   
1233                        0.0                      1.0           0.0   
1234                        0.0                      1.0           0.0   

      Race = Caucasian  Race = Hispanic  Race = Native American  Race = Other  \
0                  0.0              0.0                     0.0           0.0   
1                  0.0              1.0                     0.0           0.0   
2                  0.0              0.0                     0.0           0.0   
3                  0.0              1.0                     0.0           0.0   
4                  1.0              0.0                     0.0           0.0   
...                ...              ...                     ...           ...   
1230               1.0              0.0                     0.0           0.0   
1231               0.0              0.0                     0.0           0.0   
1232               1.0              0.0                     0.0           0.0   
1233               0.0              0.0                     0.0           0.0   
1234               0.0              0.0                     0.0           0.0   

      C_Charge_Degree = F  C_Charge_Degree = M  Priors_Count  Time_Served  
0                     0.0                  1.0          13.0          7.0  
1                     0.0                  1.0           1.0          1.0  
2                     1.0                  0.0           2.0          0.0  
3                     0.0                  1.0           0.0          0.0  
4                     1.0                  0.0           1.0          1.0  
...                   ...                  ...           ...          ...  
1230                  0.0                  1.0           0.0         42.0  
1231                  1.0                  0.0           9.0          1.0  
1232                  1.0                  0.0           6.0          0.0  
1233                  1.0                  0.0           0.0          1.0  
1234                  1.0                  0.0           2.0         86.0  

[1235 rows x 15 columns]

In [65]:
df.columns

Index(['Sex = Female', 'Sex = Male', 'Age_Cat = Less than 25',
       'Age_Cat = 25 - 45', 'Age_Cat = Greater than 45',
       'Race = African-American', 'Race = Asian', 'Race = Caucasian',
       'Race = Hispanic', 'Race = Native American', 'Race = Other',
       'C_Charge_Degree = F', 'C_Charge_Degree = M', 'Priors_Count',
       'Time_Served', 'Status'],
      dtype='object')

In [101]:
ares_data_info = AReS_dataInfo(
    X = df,
    categorical_features={
        'COMPAS':
        ['Sex = Female', 'Sex = Male',
        'Age_Cat = Less than 25','Age_Cat = 25 - 45', 'Age_Cat = Greater than 45',
        'Race = African-American', 'Race = Asian', 'Race = Caucasian','Race = Hispanic', 'Race = Native American', 'Race = Other',
        'C_Charge_Degree = F', 'C_Charge_Degree = M']
        },
    features_tree={
        'Sex': ['Sex = Female', 'Sex = Male'],
        'Age_Cat': ['Age_Cat = Less than 25', 'Age_Cat = 25 - 45', 'Age_Cat = Greater than 45'],
        'Race': ['Race = African-American','Race = Asian','Race = Caucasian','Race = Hispanic','Race = Native American','Race = Other'],
        'C_Charge_Degree': ['C_Charge_Degree = F', 'C_Charge_Degree = M'],
        'Priors_Count': [],
        'Time_Served': []
        },
    name='COMPAS',
    target_column='Status',
    one_hot_encoded=False,
    normalize=False,
    ordinal_features=[],
    dropped_features= [],
)

In [102]:
ares_data_info.features_tree

{'Sex = Female': array([0., 1.]),
 'Sex = Male': array([1., 0.]),
 'Age_Cat = Less than 25': array([0., 1.]),
 'Age_Cat = 25 - 45': array([0., 1.]),
 'Age_Cat = Greater than 45': array([1., 0.]),
 'Race = African-American': array([0., 1.]),
 'Race = Asian': array([0., 1.]),
 'Race = Caucasian': array([0., 1.]),
 'Race = Hispanic': array([0., 1.]),
 'Race = Native American': array([0., 1.]),
 'Race = Other': array([1., 0.]),
 'C_Charge_Degree = F': array([1., 0.]),
 'C_Charge_Degree = M': array([0., 1.]),
 'Priors_Count': array([ 0.,  4., 14.,  3.,  1.,  7.,  6.,  5., 13.,  8.,  9., 21.,  2.,
        15., 10., 28., 19., 11., 23., 25., 36., 12., 20., 33., 16., 18.,
        17., 22., 30., 24., 27., 26., 37., 29., 31., 38.]),
 'Time_Served': array([  0.,  10.,   1.,   6.,   2.,   4.,  14.,   3.,  17.,  37.,  44.,
         11.,  33.,  79., 135.,  23.,  13.,  18.,  30., 241.,  16.,  57.,
          7.,   9.,  12.,   5.,  38., 106., 176., 471.,   8.,  15.,  26.,
        530.,  70.,  22., 117.,

In [103]:
ares_data_info.categorical_features

{'COMPAS': ['Sex = Female',
  'Sex = Male',
  'Age_Cat = Less than 25',
  'Age_Cat = 25 - 45',
  'Age_Cat = Greater than 45',
  'Race = African-American',
  'Race = Asian',
  'Race = Caucasian',
  'Race = Hispanic',
  'Race = Native American',
  'Race = Other',
  'C_Charge_Degree = F',
  'C_Charge_Degree = M']}

In [104]:
a,b = ares_test.generate_counterfactuals(
    # dataset_ares=dataset_ares,
    dataset_ares = ares_data_info,
    data=compas_ares,
)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [19]:
a

array([[ 1.,  0.,  0., ...,  0.,  1., 29.],
       [ 0.,  1.,  1., ...,  0.,  0.,  3.],
       [ 0.,  1.,  1., ...,  0.,  2.,  1.],
       ...,
       [ 1.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  8.,  8.]])

In [20]:
b

array([[ 0.,  1.,  1., ...,  0.,  2.,  1.],
       [ 0.,  1.,  1., ...,  0.,  1.,  0.],
       [ 1.,  0.,  0., ...,  1.,  5.,  2.],
       ...,
       [ 0.,  1.,  0., ...,  0.,  1., 16.],
       [ 0.,  1.,  1., ...,  0.,  1.,  1.],
       [ 1.,  0.,  1., ...,  0.,  0.,  0.]])

##### Test the DisCount

In [21]:
from xai_cola.counterfactual_explainer import DisCount

discount_test = DisCount(
    ml_model = ml_model,
)

In [22]:
compas_ares.get_x()

Sex = Female  Sex = Male  Age_Cat = Less than 25  Age_Cat = 25 - 45  \
0              0.0         1.0                     0.0                1.0   
1              0.0         1.0                     0.0                1.0   
2              0.0         1.0                     0.0                1.0   
3              0.0         1.0                     1.0                0.0   
4              1.0         0.0                     1.0                0.0   
...            ...         ...                     ...                ...   
1230           0.0         1.0                     0.0                0.0   
1231           0.0         1.0                     0.0                1.0   
1232           0.0         1.0                     1.0                0.0   
1233           0.0         1.0                     0.0                1.0   
1234           0.0         1.0                     1.0                0.0   

      Age_Cat = Greater than 45  Race = African-American  Race = Asian  \
0                           0.0                      1.0           0.0   
1                           0.0                      0.0           0.0   
2                           0.0                      1.0           0.0   
3                           0.0                      0.0           0.0   
4                           0.0                      0.0           0.0   
...                         ...                      ...           ...   
1230                        1.0                      0.0           0.0   
1231                        0.0                      1.0           0.0   
1232                        0.0                      0.0           0.0   
1233                        0.0                      1.0           0.0   
1234                        0.0                      1.0           0.0   

      Race = Caucasian  Race = Hispanic  Race = Native American  Race = Other  \
0                  0.0              0.0                     0.0           0.0   
1                  0.0              1.0                     0.0           0.0   
2                  0.0              0.0                     0.0           0.0   
3                  0.0              1.0                     0.0           0.0   
4                  1.0              0.0                     0.0           0.0   
...                ...              ...                     ...           ...   
1230               1.0              0.0                     0.0           0.0   
1231               0.0              0.0                     0.0           0.0   
1232               1.0              0.0                     0.0           0.0   
1233               0.0              0.0                     0.0           0.0   
1234               0.0              0.0                     0.0           0.0   

      C_Charge_Degree = F  C_Charge_Degree = M  Priors_Count  Time_Served  
0                     0.0                  1.0          13.0          7.0  
1                     0.0                  1.0           1.0          1.0  
2                     1.0                  0.0           2.0          0.0  
3                     0.0                  1.0           0.0          0.0  
4                     1.0                  0.0           1.0          1.0  
...                   ...                  ...           ...          ...  
1230                  0.0                  1.0           0.0         42.0  
1231                  1.0                  0.0           9.0          1.0  
1232                  1.0                  0.0           6.0          0.0  
1233                  1.0                  0.0           0.0          1.0  
1234                  1.0                  0.0           2.0         86.0  

[1235 rows x 15 columns]

In [23]:
X_test_scaler_screwed = X_test.head(100).values

In [24]:
compas_ares_screwed = data.NumpyData(
    data=X_test_scaler_screwed, 
    target_name="Status", 
    feature_names=column_names,
    )

In [25]:
a,b = discount_test.generate_counterfactuals(
    data=compas_ares_screwed,
    lr=1e-1,
    n_proj=10,
    delta=0.05,
    U_1=0.4,
    U_2=0.3,
    l=0.2,
    r=1,
    max_iter=15,
    tau=1e1,   #差值变化 - 步长不能太大或者太小
    silent=False,
    )

INFO:root:Optimization started
  0%|          | 0/15 [00:00<?, ?it/s]INFO:root:U_1-Qu_upper=0.4, U_2-Qv_upper=-0.5444173482861057
INFO:root:eta=1, l=0.24000000000000002, r=1
INFO:root:Iter 1: Q = 0.4802275598049164, term1 = 0.00095703563420102, term2 = 0.4802275598049164
  7%|▋         | 1/15 [00:09<02:16,  9.74s/it]INFO:root:U_1-Qu_upper=0.4, U_2-Qv_upper=-0.5211320466167337
INFO:root:eta=1, l=0.278, r=1
INFO:root:Iter 2: Q = 0.460342675447464, term1 = 0.0009603290818631649, term2 = 0.460342675447464
 13%|█▎        | 2/15 [00:19<02:09,  9.96s/it]INFO:root:U_1-Qu_upper=0.4, U_2-Qv_upper=-0.5104814962653772
INFO:root:eta=1, l=0.31410000000000005, r=1
INFO:root:Iter 3: Q = 0.44128137826919556, term1 = 0.0009664438548497856, term2 = 0.44128137826919556
 20%|██        | 3/15 [00:30<02:02, 10.23s/it]INFO:root:U_1-Qu_upper=0.4, U_2-Qv_upper=-0.4931948738717254
INFO:root:eta=1, l=0.34839500000000007, r=1
INFO:root:Iter 4: Q = 0.42300930619239807, term1 = 0.000975792296230793, term2 = 0.423009

In [26]:
a

array([[ 0.,  1.,  0., ...,  1., 13.,  7.],
       [ 0.,  1.,  0., ...,  1.,  1.,  1.],
       [ 0.,  1.,  0., ...,  0.,  2.,  0.],
       ...,
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  5., 54.],
       [ 0.,  1.,  0., ...,  1.,  0.,  0.]])

In [27]:
b

array([[-4.24781889e-02,  9.98884082e-01,  7.77557567e-02, ...,
        -7.31216520e-02,  1.02073979e+00,  9.93877590e-01],
       [ 9.92875218e-01,  1.96001842e-03, -7.99882878e-03, ...,
         1.39615135e-02, -1.06622120e-02, -1.12596257e-02],
       [ 9.12675381e-01, -9.14915465e-03,  1.05884224e-01, ...,
         9.02045310e-01,  2.79741697e-02,  2.01462460e+00],
       ...,
       [ 9.97708976e-01,  2.32858863e-03,  1.01004827e+00, ...,
        -1.25555228e-03,  1.00761521e+00,  1.00938368e+00],
       [-2.10487191e-02,  9.82927382e-01,  5.89253940e-02, ...,
         9.50401068e-01,  2.01774144e+00,  4.99283361e+00],
       [-1.26701901e-02,  1.00107181e+00,  8.17045942e-03, ...,
        -2.68537682e-02,  3.02676463e+00, -1.08852182e-02]], dtype=float32)

##### DisCOUNT test on scalered Compas dataset

In [28]:
scaler = StandardScaler()

# Assume df is your DataFrame and 'target' is your target column
X = df.drop(columns=['Status'])
Y = df['Status']

# Step 1: Split the Data
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

print(f'X_train_scaler: {X_train_scaler.shape}')
print(f'X_test_scaler: {X_test_scaler.shape}')

X_train_scaler: (4937, 15)
X_test_scaler: (1235, 15)


In [29]:
input_dim = X_train_scaler.shape[1]

model_svm_scaler = PyTorchLinearSVM(input_dim)

# 定义损失函数和优化器
criterion = nn.BCEWithLogitsLoss()  # 二分类任务中的损失函数
optimizer = optim.Adam(model_svm.parameters(), lr=0.01)  # 使用Adam优化器

# 数据转换为 PyTorch tensor 格式
X_train_tensor = torch.FloatTensor(X_train_scaler)
y_train_tensor = torch.FloatTensor(y_train).view(-1, 1)  # 确保y是二维



# 训练模型
epochs = 400  # 训练次数
for epoch in range(epochs):
    model_svm.train()  # 进入训练模式
    # 前向传播
    outputs = model_svm(X_train_tensor)
    # 计算损失
    loss = criterion(outputs, y_train_tensor)
    # 梯度清零
    optimizer.zero_grad()
    # 反向传播
    loss.backward()
    # 优化更新参数
    optimizer.step()
    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}')

Epoch [10/400], Loss: 0.6749
Epoch [20/400], Loss: 0.6451
Epoch [30/400], Loss: 0.6263
Epoch [40/400], Loss: 0.6164
Epoch [50/400], Loss: 0.6117
Epoch [60/400], Loss: 0.6099
Epoch [70/400], Loss: 0.6091
Epoch [80/400], Loss: 0.6087
Epoch [90/400], Loss: 0.6085
Epoch [100/400], Loss: 0.6083
Epoch [110/400], Loss: 0.6082
Epoch [120/400], Loss: 0.6081
Epoch [130/400], Loss: 0.6080
Epoch [140/400], Loss: 0.6080
Epoch [150/400], Loss: 0.6080
Epoch [160/400], Loss: 0.6080
Epoch [170/400], Loss: 0.6080
Epoch [180/400], Loss: 0.6080
Epoch [190/400], Loss: 0.6080
Epoch [200/400], Loss: 0.6080
Epoch [210/400], Loss: 0.6080
Epoch [220/400], Loss: 0.6080
Epoch [230/400], Loss: 0.6080
Epoch [240/400], Loss: 0.6080
Epoch [250/400], Loss: 0.6080
Epoch [260/400], Loss: 0.6080
Epoch [270/400], Loss: 0.6080
Epoch [280/400], Loss: 0.6080
Epoch [290/400], Loss: 0.6080
Epoch [300/400], Loss: 0.6080
Epoch [310/400], Loss: 0.6080
Epoch [320/400], Loss: 0.6080
Epoch [330/400], Loss: 0.6080
Epoch [340/400], Lo

In [30]:
ml_model_scaler = Model(model_svm_scaler,'PYT')
compas_ares_scaler_test = data.NumpyData(
    data=X_test_scaler, 
    target_name="Status", 
    feature_names=column_names,
    )

In [31]:
discount_test_scaler = DisCount(ml_model = ml_model_scaler)

In [35]:
compas_ares_scaler_test.get_x()

Sex = Female  Sex = Male  Age_Cat = Less than 25  Age_Cat = 25 - 45  \
0        -0.482399    0.482399               -0.521627           0.859291   
1        -0.482399    0.482399               -0.521627           0.859291   
2        -0.482399    0.482399               -0.521627           0.859291   
3        -0.482399    0.482399                1.917078          -1.163751   
4         2.072971   -2.072971                1.917078          -1.163751   
...            ...         ...                     ...                ...   
1230     -0.482399    0.482399               -0.521627          -1.163751   
1231     -0.482399    0.482399               -0.521627           0.859291   
1232     -0.482399    0.482399                1.917078          -1.163751   
1233     -0.482399    0.482399               -0.521627           0.859291   
1234     -0.482399    0.482399                1.917078          -1.163751   

      Age_Cat = Greater than 45  Race = African-American  Race = Asian  \
0                     -0.516911                 0.963204     -0.075524   
1                     -0.516911                -1.038201     -0.075524   
2                     -0.516911                 0.963204     -0.075524   
3                     -0.516911                -1.038201     -0.075524   
4                     -0.516911                -1.038201     -0.075524   
...                         ...                      ...           ...   
1230                   1.934568                -1.038201     -0.075524   
1231                  -0.516911                 0.963204     -0.075524   
1232                  -0.516911                -1.038201     -0.075524   
1233                  -0.516911                 0.963204     -0.075524   
1234                  -0.516911                 0.963204     -0.075524   

      Race = Caucasian  Race = Hispanic  Race = Native American  Race = Other  \
0            -0.708181        -0.300544               -0.040287      -0.24613   
1            -0.708181         3.327297               -0.040287      -0.24613   
2            -0.708181        -0.300544               -0.040287      -0.24613   
3            -0.708181         3.327297               -0.040287      -0.24613   
4             1.412068        -0.300544               -0.040287      -0.24613   
...                ...              ...                     ...           ...   
1230          1.412068        -0.300544               -0.040287      -0.24613   
1231         -0.708181        -0.300544               -0.040287      -0.24613   
1232          1.412068        -0.300544               -0.040287      -0.24613   
1233         -0.708181        -0.300544               -0.040287      -0.24613   
1234         -0.708181        -0.300544               -0.040287      -0.24613   

      C_Charge_Degree = F  C_Charge_Degree = M  Priors_Count  Time_Served  
0               -1.352489             1.352489      2.055454    -0.161851  
1               -1.352489             1.352489     -0.481384    -0.292683  
2                0.739378            -0.739378     -0.269981    -0.314488  
3               -1.352489             1.352489     -0.692787    -0.314488  
4                0.739378            -0.739378     -0.481384    -0.292683  
...                   ...                  ...           ...          ...  
1230            -1.352489             1.352489     -0.692787     0.601337  
1231             0.739378            -0.739378      1.209841    -0.292683  
1232             0.739378            -0.739378      0.575631    -0.314488  
1233             0.739378            -0.739378     -0.692787    -0.292683  
1234             0.739378            -0.739378     -0.269981     1.560772  

[1235 rows x 15 columns]

In [36]:
FACTUAL,COUNTERFACTUAL = discount_test_scaler.generate_counterfactuals(
    data=compas_ares_scaler_test,
    lr=1e-1,
    n_proj=10,
    delta=0.05,
    U_1=0.4,
    U_2=0.3,
    l=0.2,
    r=1,
    max_iter=15,
    tau=1e1,   #差值变化 - 步长不能太大或者太小
    silent=False,
)

INFO:root:Optimization started
  0%|          | 0/15 [00:31<?, ?it/s]


KeyboardInterrupt: 

In [57]:
FACTUAL

array([[-0.48239933,  0.48239933, -0.52162709,  0.85929057, -0.51691114,
        -1.03820131, -0.07552357,  1.41206789, -0.30054426, -0.04028706,
        -0.24613009, -1.35248895,  1.35248895, -0.05857799, -0.24907213],
       [-0.48239933,  0.48239933, -0.52162709,  0.85929057, -0.51691114,
        -1.03820131, -0.07552357, -0.70818125,  3.3272969 , -0.04028706,
        -0.24613009, -1.35248895,  1.35248895, -0.26998115, -0.31448817],
       [-0.48239933,  0.48239933, -0.52162709,  0.85929057, -0.51691114,
        -1.03820131, -0.07552357,  1.41206789, -0.30054426, -0.04028706,
        -0.24613009, -1.35248895,  1.35248895, -0.05857799, -0.11824003],
       [-0.48239933,  0.48239933, -0.52162709,  0.85929057, -0.51691114,
        -1.03820131, -0.07552357,  1.41206789, -0.30054426, -0.04028706,
        -0.24613009, -1.35248895,  1.35248895, -0.69278746,  0.09981347]])

In [58]:
COUNTERFACTUAL

array([[ 7.60768632e+19, -2.43854109e+19, -1.01902936e+19,
         1.70677168e+19, -1.07778581e+20,  2.39597284e+19,
        -4.28363441e+19, -7.02984370e+19,  6.71706002e+18,
        -8.49078239e+19,  6.11193445e+19, -4.84563878e+19,
        -1.46901025e+20,  1.82407671e+19,  3.46833972e+19],
       [ 1.51145817e+20, -5.84598986e+19, -3.55969194e+20,
        -8.29703437e+19, -9.97626658e+19, -1.38731473e+19,
         2.25533532e+20, -2.98642311e+19, -1.08800018e+20,
        -8.72218825e+18, -1.39998520e+20, -3.07962722e+20,
        -1.41065741e+20,  2.90366296e+20, -5.22937318e+19],
       [ 6.58518774e+16,  5.37129847e+17, -5.43214819e+17,
        -3.98472154e+17, -3.79203487e+17,  5.74257572e+17,
        -1.10609702e+18, -3.79699590e+15,  1.01860633e+18,
        -1.06010115e+18, -9.68061749e+16, -1.01201112e+18,
        -8.48801880e+17,  1.09700670e+16, -8.94914985e+17],
       [ 2.21090431e+20, -1.55575354e+20, -3.31973769e+20,
         1.30074163e+18, -8.29704756e+19, -3.98146091

In [59]:
inversed = scaler.inverse_transform(COUNTERFACTUAL)
inversed

array([[ 2.9771360e+19, -9.5428077e+18, -4.1785667e+18,  8.4366627e+18,
        -4.3964707e+19,  1.1971451e+19, -3.2168054e+18, -3.3155745e+19,
         1.8515309e+18, -3.4151439e+18,  1.4184041e+19, -2.3164188e+19,
        -7.0224858e+19,  8.6284272e+19,  1.5905912e+21],
       [ 5.9148294e+19, -2.2877268e+19, -1.4596646e+20, -4.1012681e+19,
        -4.0694878e+19, -6.9317017e+18,  1.6936494e+19, -1.4085246e+19,
        -2.9990292e+19, -3.5082193e+17, -3.2489625e+19, -1.4721911e+20,
        -6.7435344e+19,  1.3735192e+21, -2.3982065e+21],
       [ 2.5769991e+16,  2.1019646e+17, -2.2274721e+17, -1.9696689e+17,
        -1.5468352e+17,  2.8692713e+17, -8.3062623e+16, -1.7908254e+15,
         2.8077479e+17, -4.2639155e+16, -2.2465926e+16, -4.8378378e+17,
        -4.0576291e+17,  5.1891687e+16, -4.1041075e+19],
       [ 8.6519901e+19, -6.0881718e+19, -1.3612704e+20,  6.4296348e+17,
        -3.3845059e+19, -1.9893323e+19,  2.2050103e+19,  2.7577885e+19,
        -5.9864877e+19,  2.9658323e+1